// ts2fable 0.7.1
module rec Profile
open System
open Fable.Core
open Fable.Core.JS

/// Identifies an attribute with a name and a container.
type [<AllowNullLiteral>] AttributeDescriptor =
    /// The name of the attribute.
    abstract attributeName: string with get, set
    /// The container the attribute resides in.
    abstract containerName: string with get, set

/// Stores a set of named profile attributes.
type [<AllowNullLiteral>] AttributesContainer =
    /// The attributes stored by the container.
    abstract attributes: AttributesContainerAttributes with get, set
    /// The name of the container.
    abstract containerName: string with get, set
    /// The maximum revision number of any attribute within the container.
    abstract revision: int with get, set

type [<AllowNullLiteral>] Avatar =
    abstract isAutoGenerated: bool with get, set
    abstract size: AvatarSize with get, set
    abstract timeStamp: DateTime with get, set
    abstract value: ResizeArray<float> with get, set

type [<RequireQualifiedAccess>] AvatarSize =
    | Small = 0
    | Medium = 1
    | Large = 2

/// A profile attribute which always has a value for each profile.
type [<AllowNullLiteral>] CoreProfileAttribute =
    inherit ProfileAttributeBase<obj option>

type [<AllowNullLiteral>] CreateProfileContext =
    abstract ciData: CreateProfileContextCiData with get, set
    abstract contactWithOffers: bool with get, set
    abstract countryName: string with get, set
    abstract displayName: string with get, set
    abstract emailAddress: string with get, set
    abstract hasAccount: bool with get, set
    abstract language: string with get, set
    abstract phoneNumber: string with get, set
    /// The current state of the profile.
    abstract profileState: ProfileState with get, set

type [<AllowNullLiteral>] GeoRegion =
    abstract regionCode: string with get, set

/// A user profile.
type [<AllowNullLiteral>] Profile =
    /// The attributes of this profile.
    abstract applicationContainer: AttributesContainer with get, set
    /// The core attributes of this profile.
    abstract coreAttributes: ProfileCoreAttributes with get, set
    /// The maximum revision number of any attribute.
    abstract coreRevision: int with get, set
    /// The unique identifier of the profile.
    abstract id: string with get, set
    /// The current state of the profile.
    abstract profileState: ProfileState with get, set
    /// The maximum revision number of any attribute.
    abstract revision: int with get, set
    /// The time at which this profile was last changed.
    abstract timeStamp: DateTime with get, set

/// A named object associated with a profile.
type [<AllowNullLiteral>] ProfileAttribute =
    inherit ProfileAttributeBase<string>

type [<AllowNullLiteral>] ProfileAttributeBase<'T> =
    /// The descriptor of the attribute.
    abstract descriptor: AttributeDescriptor with get, set
    /// The revision number of the attribute.
    abstract revision: int with get, set
    /// The time the attribute was last changed.
    abstract timeStamp: DateTime with get, set
    /// The value of the attribute.
    abstract value: 'T with get, set

/// Country/region information
type [<AllowNullLiteral>] ProfileRegion =
    /// The two-letter code defined in ISO 3166 for the country/region.
    abstract code: string with get, set
    /// Localized country/region name
    abstract name: string with get, set

/// Container of country/region information
type [<AllowNullLiteral>] ProfileRegions =
    /// List of country/region code with contact consent requirement type of notice
    abstract noticeContactConsentRequirementRegions: ResizeArray<string> with get, set
    /// List of country/region code with contact consent requirement type of opt-out
    abstract optOutContactConsentRequirementRegions: ResizeArray<string> with get, set
    /// List of country/regions
    abstract regions: ResizeArray<ProfileRegion> with get, set

type [<RequireQualifiedAccess>] ProfileState =
    | Custom = 0
    | CustomReadOnly = 1
    | ReadOnly = 2

type [<AllowNullLiteral>] AttributesContainerAttributes =
    [<Emit "$0[$1]{{=$2}}">] abstract Item: key: string -> ProfileAttribute with get, set

type [<AllowNullLiteral>] CreateProfileContextCiData =
    [<Emit "$0[$1]{{=$2}}">] abstract Item: key: string -> obj option with get, set

type [<AllowNullLiteral>] ProfileCoreAttributes =
    [<Emit "$0[$1]{{=$2}}">] abstract Item: key: string -> CoreProfileAttribute with get, set
